version: '2.2'
services:
  eventforwarder:
    build:
      context: .
      args:
        INIFILE: cb-event-forwarder.docker.ini
        EFEXE: cb-event-forwarder
    hostname: eventforwarder
    container_name: eventforwarder
    restart: always
    cpu_count: 6
    tty: true
    environment:
      - EF_CANNED_INPUT=/bundleone
    sysctls:
      net.ipv6.conf.all.disable_ipv6 :  1
    ports:
      - "33706:33706"
    depends_on:
      - grafana
      - graphite
      - s3server

  grafana:
      image: grafana/grafana
      container_name: grafana
      hostname: grafana
      restart: always
      ports:
        - 3000:3000

  graphite:
      hostname: graphite
      image: graphiteapp/graphite-statsd
      container_name: graphite
      restart: always

  s3server:
      container_name: s3server
      hostname: s3serer
      tty: true
      environment:
        - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
        - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      build:
        context: .
        dockerfile: Dockerfile.s3server
      restart: always
      command: server /tmp
      ports:
        - 9000:9000
